version: '3'

services:
  web:
    build: .
    command: bash -c 'while !</dev/tcp/db/5432; do sleep 1; done; uvicorn pslibrary.main:app --host 0.0.0.0'
    volumes:
      - .:/code
    ports:
      - "8000:8000"
    environment:
      - DATABASE_URL=postgresql://pslibrary:pslibrary@db:5432/pslibrary
    depends_on:
      - db

  db:
    image: postgres:15-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    expose:
      - 5432
    environment:
      - POSTGRES_USER=pslibrary
      - POSTGRES_PASSWORD=pslibrary
      - POSTGRES_DB=pslibrary

volumes:
  postgres_data:
 